// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class spaceportRegistered extends ethereum.Event {
  get params(): spaceportRegistered__Params {
    return new spaceportRegistered__Params(this);
  }
}

export class spaceportRegistered__Params {
  _event: spaceportRegistered;

  constructor(event: spaceportRegistered) {
    this._event = event;
  }

  get spaceportContract(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class SpaceportFactory extends ethereum.SmartContract {
  static bind(address: Address): SpaceportFactory {
    return new SpaceportFactory("SpaceportFactory", address);
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  spaceportAtIndex(_index: BigInt): Address {
    let result = super.call(
      "spaceportAtIndex",
      "spaceportAtIndex(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(_index)]
    );

    return result[0].toAddress();
  }

  try_spaceportAtIndex(_index: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "spaceportAtIndex",
      "spaceportAtIndex(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(_index)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  spaceportGeneratorAtIndex(_index: BigInt): Address {
    let result = super.call(
      "spaceportGeneratorAtIndex",
      "spaceportGeneratorAtIndex(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(_index)]
    );

    return result[0].toAddress();
  }

  try_spaceportGeneratorAtIndex(_index: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "spaceportGeneratorAtIndex",
      "spaceportGeneratorAtIndex(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(_index)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  spaceportGeneratorsLength(): BigInt {
    let result = super.call(
      "spaceportGeneratorsLength",
      "spaceportGeneratorsLength():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_spaceportGeneratorsLength(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "spaceportGeneratorsLength",
      "spaceportGeneratorsLength():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  spaceportIsRegistered(_spaceportAddress: Address): boolean {
    let result = super.call(
      "spaceportIsRegistered",
      "spaceportIsRegistered(address):(bool)",
      [ethereum.Value.fromAddress(_spaceportAddress)]
    );

    return result[0].toBoolean();
  }

  try_spaceportIsRegistered(
    _spaceportAddress: Address
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "spaceportIsRegistered",
      "spaceportIsRegistered(address):(bool)",
      [ethereum.Value.fromAddress(_spaceportAddress)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  spaceportsLength(): BigInt {
    let result = super.call(
      "spaceportsLength",
      "spaceportsLength():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_spaceportsLength(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "spaceportsLength",
      "spaceportsLength():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }
}

export class AdminAllowSpaceportGeneratorCall extends ethereum.Call {
  get inputs(): AdminAllowSpaceportGeneratorCall__Inputs {
    return new AdminAllowSpaceportGeneratorCall__Inputs(this);
  }

  get outputs(): AdminAllowSpaceportGeneratorCall__Outputs {
    return new AdminAllowSpaceportGeneratorCall__Outputs(this);
  }
}

export class AdminAllowSpaceportGeneratorCall__Inputs {
  _call: AdminAllowSpaceportGeneratorCall;

  constructor(call: AdminAllowSpaceportGeneratorCall) {
    this._call = call;
  }

  get _address(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _allow(): boolean {
    return this._call.inputValues[1].value.toBoolean();
  }
}

export class AdminAllowSpaceportGeneratorCall__Outputs {
  _call: AdminAllowSpaceportGeneratorCall;

  constructor(call: AdminAllowSpaceportGeneratorCall) {
    this._call = call;
  }
}

export class RegisterSpaceportCall extends ethereum.Call {
  get inputs(): RegisterSpaceportCall__Inputs {
    return new RegisterSpaceportCall__Inputs(this);
  }

  get outputs(): RegisterSpaceportCall__Outputs {
    return new RegisterSpaceportCall__Outputs(this);
  }
}

export class RegisterSpaceportCall__Inputs {
  _call: RegisterSpaceportCall;

  constructor(call: RegisterSpaceportCall) {
    this._call = call;
  }

  get _spaceportAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class RegisterSpaceportCall__Outputs {
  _call: RegisterSpaceportCall;

  constructor(call: RegisterSpaceportCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}
